---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webflask-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: criticalhitx/webflask:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webflask-service
  labels:
    app: flask
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 80
