apiVersion: v1
kind: Service
metadata:
  name: myapp1-mysql
  labels:
    app: myapp1
spec:
  ports:
    - port: 3306
  selector:
    app: myapp1
    tier: mysql
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-myapp1-mysql
  labels:
    app: myapp1
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-mysql
  labels:
    app: myapp1
spec:
  selector:
    matchLabels:
      app: myapp1
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp1
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: root-pass
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-myapp1-mysql
