---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-myapp1-mysql
  labels:
    app: myapp1
spec:
  storageClassName: "standard"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pv-myapp1-mysql
    fsType: ext4
