---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-mysql-v1
  labels:
    name: my-mysql
    version: v1
spec:
  replicas: 1
  selector:
    name: my-mysql
    version: v1
  template:
    metadata:
      labels:
        name: my-mysql
        version: v1
    spec:
      containers:
        - image: docker.io/mysql
          name: my-mysql-v1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: toor
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
